"""init tables

Revision ID: d720b1d6e7ee
Revises: 
Create Date: 2021-06-30 02:20:39.131612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd720b1d6e7ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('currency_title', sa.String(), nullable=True),
        sa.Column('currency_symbol', sa.String(), nullable=True),
        sa.Column('currency_type', sa.String(), nullable=True),
        sa.Column('rate_used', sa.String(), nullable=True),
        sa.Column('timestamp', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
