pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        parallel(
          "Load from one source": {
            sh 'echo loading'
          },
          "Load from other source": {
            sh 'echo loading'
          }
        )
      }
    }
    stage('Transform') {
      steps {
        parallel(
          "Transform meta": {
            sh 'echo Hello'
          },
          "Transform success file": {
            sh 'echo Hello'
          }
        )
      }
    }
    stage('Upload') {
      steps {
        parallel(
          "Upload to postgres": {
            sh 'echo Hello'
          },
          "Upload to hadoop": {
            sh 'echo Hello'
          },
          "Upload to impala": {
            sh 'echo Hello'
          }
        )
      }
    }
    stage('Check branch') {
      steps {
        script {
          if (env.BRANCH_NAME == 'master') {
              echo 'I only execute on the master branch'
          } else {
              echo 'I execute elsewhere'
          }
      }
    }
  }
}
