pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        parallel(
          "Load from one source": {
            sh 'echo loading'
          },
          "Load from other source": {
            sh 'echo loading'
          }
        )
      }
    }
    stage('Transform') {
      steps {
        parallel(
          "Transform meta": {
            sh 'echo Hello'
          },
          "Transform success file": {
            sh 'echo Hello'
          }
        )
      }
    }
    stage('Upload') {
      steps {
        parallel(
          "Upload to postgres": {
            sh 'echo Hello'
          },
          "Upload to hadoop": {
            sh 'echo Hello'
          },
          "Upload to impala": {
            sh 'echo Hello'
          }
        )
      }
    }
    stage('Check true') {
      steps {
        script {
          if (true) {
            stage ('Stage 1') {
              sh 'echo Stage 1'
            }
          }
          else {
            stage ('Stage 2') {
              sh 'echo Stage 2'
            }
          }
        }
      }
    }
  }
}
